### ISSUE TITLE
error about invalid messages

### ISSUE THREAD

**Issue by asdfawjbhsdhbasjindh** [MoleTheDev/DankMemer-Farmer#11]
![image](https://user-images.githubusercontent.com/88472260/192064011-84b50e10-6f38-45d3-bace-eab8118a3f34.png)

it just sends me the error every time I start it but it says its sending messages in the terminal but its actually not

**Comment by MoleTheDev** [comment]
This is because i used ```Discord.py 1.7.6``` commands 

I will update to latest discord.py version tmrw

**Comment by asdfawjbhsdhbasjindh** [comment]
alright thanks

**Comment by MoleTheDev** [comment]
Discord.py does not support self-bots anymore
You can look into Discord.py 1.7.3 and 2.0.1 source code, they removed the ```bot``` parameter from ```client.run```.
![image](https://user-images.githubusercontent.com/93382765/192138841-9ba27172-7863-4ec7-8d67-b6bfe7f2e93f.png)
When a user token is passed and ```bot``` parameter is not set to ```False``` it will trigger the error ```discord.errors.LoginFailure: Improper token has been passed``` because it's a user token, not a bot token. and now the ability to pass user tokens is removed.
So, even if I updated it to 2.0.1 it won't work

Maybe i will re-write it in Node.js using [discordjs-self-v13](https://discordjs-self-v13.netlify.app/#/) in the future

**Comment by MoleTheDev** [comment]
Done, you can use it now
